Qorum manager cluster create FINISHED

diff --git a/cookbooks/gpfsinstall/templates/rhel2.erb b/cookbooks/gpfsinstall/templates/rhel2.erb
--- a/cookbooks/gpfsinstall/templates/rhel2.erb
+++ b/cookbooks/gpfsinstall/templates/rhel2.erb
@@ -4,6 +4,70 @@ Vagrant.configure("2") do |config|
 
 
 
+
+
+$script = << BASH
+
+	ls /vagrant/Spectrum_Scale_Advanced-4.2.1.0-x86_64-Linux-install
+
+		if [ $? -ne 0 ]
+		then
+			echo "GPFS INSTALLER NOT FOUND IN /vagrant You`re not Authorized to have the GPFS Installer :) Contact Robert Nicoara ASAP on ST Internal Messenger "
+		else
+			mkdir -p /root/gpfspack ; cd /root/gpfspack ; cp /vagrant/Spectrum_Scale_Advanced-4.2.1.0-x86_64-Linux-install . ;  tar -xvf SpectrumScaleAdv421LXx86.tgz ; chmod +x Spectrum_Scale_Advanced-4.2.1.0-x86_64-Linux-install ; ./Spectrum_Scale_Advanced-4.2.1.0-x86_64-Linux-install --text-only --silent
+			cd /usr/lpp/mmfs/4.2.1.0 ; mkdir need ; cd need
+
+#STARTING for to move base needded files 
+
+     			for pack in gpfs.ext-*.x86_64.rpm gpfs.docs-*.noarch.rpm kmod-gpfs-*.sdl6.x86_64.rpm gpfs.base-*.x86_64.rpm gpfs.gskit-*.x86_64.rpm gpfs.msg.en_US-*.noarch.rpm gpfs.gpl-*.noarch.rpm
+	         		do
+			    	cp ../$pack .
+				done
+
+	# Begining local install
+	       yum localinstall *rpm 
+
+	# Adding second first ( this) and second host ips in /etc/hosts
+		echo >> "192.168.0.157		gpfs01.learning.learn gpfs01" >> /etc/hosts
+		echo >> "192.168.0.158		gpfs02.learning.learn gpfs02" >> /etc/hosts
+
+	# Making hosts love each other ( SSH Authorized_keys)
+
+		ssh-keygen -f /root/.ssh/id_rsa -t rsa -N '' #<--- Here we generate the key without passphrase 
+
+	
+
+     # Setting the same KHeaders / kernel / versions ... 
+
+    yum install kernel-devel-2.6.32-504.12.2.el6
+    yum install imake gcc-c++ rpm-build
+
+    # GPFS portability layer (making gpfs access the LIN Kern ) 
+
+    	cd /usr/lpp/mmfs/src ; make Autoconfig ; make World ; make InstallImages ; make rpm   #<-- This will generate an RPM needed on all nodes 
+
+
+
+    	# Installing the RPM on LocalHost as well
+    		yum localinstall /root/rpmbuild/RPMS/x86_64/*rpm
+
+
+
+    		ssh-copy-id root@gpfs01
+
+
+  
+fi
+   BASH
+
+
+
+
+
+
+
+
+
  config.vm.network "public_network", ip: "192.168.0.158", bridge: "enp1s5", adapter: 2
 
 
